[package]
name = "sonance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
thiserror = "1.0.31"

[dev-dependencies]
pretty_assertions = "1.2.1"
